name: daisy_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^14.0.0
  pie_chart: ^5.2.1
  fl_chart: ^0.63.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
